[package]
name = "barnes-hut"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
nannou = "0.18.1"
rand_distr = "0.4.3"
